import { GoogleGenAI, Type } from "@google/genai";
import { RepoContext, VibeAnalysisResult } from '../types';

export const analyzeRepoVibe = async (context: RepoContext): Promise<VibeAnalysisResult> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API_KEY environment variable is missing.");
  }

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
    You are an expert software engineer and code anthropologist. 
    Analyze the following GitHub repository metadata to determine if it was "Vibe Coded".
    
    "Vibe Coding" refers to a coding style heavily assisted or entirely generated by AI tools (Cursor, Windsurf, GitHub Copilot, Replit AI, etc.), 
    often characterized by:
    1. Presence of specific configuration files (e.g., .cursorrules, .windsurfrules).
    2. Commit messages that sound machine-generated (e.g., overly verbose, "Update [feature]", or explicit mentions of AI).
    3. High velocity of commits with broad changes.
    4. Code that feels "generated" (perfect boilerplate, generic comments).
    5. A mix of extremely high-level logic implementation with potentially messy or standard boilerplate structure.

    Repository Context:
    - Name: ${context.metadata.full_name}
    - Description: ${context.metadata.description}
    - Root Files: ${JSON.stringify(context.fileStructure)}
    - Config Files Found: ${Object.keys(context.configFileContents).join(', ')}
    - Config File Content Snippets: ${JSON.stringify(context.configFileContents)}
    - Recent Commits: ${JSON.stringify(context.recentCommits.map(c => c.message).slice(0, 15))}
    - Readme Snippet: ${context.readmeContent ? context.readmeContent.substring(0, 1000) : 'No README'}

    Analyze the evidence. Return a JSON object with:
    - score: A number 0-100 representing the probability/intensity of being Vibe Coded (0 = Hand-crafted assembly, 100 = 100% AI generated).
    - verdict: A short, catchy title for the coding style (e.g., "Cursor Native", "Human-AI Hybrid", "Old School Artisan").
    - reasoning: A paragraph explaining why you gave this score.
    - evidence: An array of strings citing specific files, commits, or patterns found.
    - aiToolsDetected: An array of specific tools detected (e.g. "Cursor", "Windsurf") or "Generic LLM" if unsure but likely.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            score: { type: Type.INTEGER },
            verdict: { type: Type.STRING },
            reasoning: { type: Type.STRING },
            evidence: { 
              type: Type.ARRAY,
              items: { type: Type.STRING }
            },
            aiToolsDetected: {
              type: Type.ARRAY,
              items: { type: Type.STRING }
            }
          },
          required: ['score', 'verdict', 'reasoning', 'evidence', 'aiToolsDetected']
        }
      }
    });

    const text = response.text;
    if (!text) throw new Error("No response from Gemini");
    
    return JSON.parse(text) as VibeAnalysisResult;

  } catch (error) {
    console.error("Gemini Analysis Error:", error);
    throw new Error("Failed to analyze the repository vibe.");
  }
};